# -*- coding: utf-8 -*-
"""AI HEALTH CARE BOT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qhgb-BX5e-qpmmsaGqgXwmrvCtmwG0yL
"""

!pip install gradio

import gradio as gr

# Define the healthcare questions and answers
healthcare_qna = {
    "What are the symptoms of diabetes?": "Common symptoms of diabetes include frequent urination, excessive thirst, unexplained weight loss, fatigue, blurred vision, and slow-healing sores.",
    "How can I prevent heart disease?": "To prevent heart disease, maintain a healthy diet, exercise regularly, avoid smoking, manage stress, and keep blood pressure and cholesterol levels in check.",
    "What are the early signs of cancer?": "Early signs of cancer can vary depending on the type but may include unusual lumps or swelling, persistent pain, changes in skin or moles, unexplained weight loss, and persistent cough or hoarseness.",
    "What are the common symptoms of influenza (flu)?": "Symptoms of influenza include high fever, chills, muscle aches, cough, congestion, runny nose, headaches, and fatigue.",
    "How is hypertension treated?": "Hypertension is treated with lifestyle changes such as a healthy diet, regular exercise, and medications like diuretics, ACE inhibitors, or beta-blockers as prescribed by a doctor.",
    "What causes allergies and how can they be managed?": "Allergies are caused by an overreaction of the immune system to allergens such as pollen, dust, or certain foods. They can be managed with medications, avoiding allergens, and using air purifiers.",
    "What are the symptoms of asthma?": "Symptoms of asthma include shortness of breath, wheezing, chest tightness, and coughing, especially at night or early in the morning.",
    "How can I manage chronic pain?": "Chronic pain can be managed through medications, physical therapy, stress management techniques, and lifestyle changes such as regular exercise and a balanced diet.",
    "What are the common treatments for arthritis?": "Treatments for arthritis include medications to reduce inflammation and pain, physical therapy, regular exercise, and in some cases, surgical interventions.",
    "What are the symptoms of a stroke?": "Symptoms of a stroke can include sudden numbness or weakness in the face, arm, or leg, confusion, trouble speaking or understanding, trouble seeing in one or both eyes, and difficulty walking or loss of balance.",
    "How can I manage diabetes?": "Diabetes management includes monitoring blood sugar levels, following a healthy diet, engaging in regular physical activity, and adhering to prescribed medications or insulin therapy.",
    "What is the difference between type 1 and type 2 diabetes?": "Type 1 diabetes is an autoimmune condition where the body does not produce insulin, while type 2 diabetes is often related to insulin resistance and is more common in adults. Both require management of blood sugar levels.",
    "What are the symptoms of high blood pressure?": "High blood pressure often has no symptoms but may include headaches, shortness of breath, or nosebleeds in severe cases.",
    "How can I reduce stress?": "Stress can be reduced through regular physical activity, relaxation techniques, meditation, maintaining a balanced diet, and seeking support from friends or a mental health professional.",
    "What is a healthy diet?": "A healthy diet includes a variety of fruits, vegetables, whole grains, lean proteins, and healthy fats, while limiting processed foods, sugary drinks, and high-sodium products.",
    "What are common causes of fatigue?": "Common causes of fatigue include poor sleep, stress, nutritional deficiencies, chronic illnesses, and lack of physical activity.",
    "How can I improve my sleep quality?": "Improving sleep quality can involve maintaining a regular sleep schedule, creating a relaxing bedtime routine, limiting caffeine and electronic device use before bed, and ensuring a comfortable sleep environment.",
    "What are the signs of dehydration?": "Signs of dehydration include dry mouth, dark yellow urine, fatigue, dizziness, and confusion.",
    "How can I boost my immune system?": "Boosting the immune system involves eating a balanced diet rich in vitamins and minerals, getting regular exercise, staying hydrated, and getting adequate sleep.",
    "What is the role of exercise in health?": "Exercise improves cardiovascular health, strengthens muscles, enhances flexibility, aids in weight management, and contributes to mental well-being.",
    "How can I manage cholesterol levels?": "Cholesterol levels can be managed through a healthy diet low in saturated fats, regular physical activity, maintaining a healthy weight, and, if necessary, medications prescribed by a doctor."
}

# Function to display the answer
def healthcare_bot(question):
    answer = healthcare_qna.get(question, "Sorry, I don't have information on that topic.")
    return answer

# Create a dropdown interface with Gradio
interface = gr.Interface(
    fn=healthcare_bot,
    inputs=gr.Dropdown(choices=list(healthcare_qna.keys()), label="Select a question"),
    outputs=gr.Textbox(label="Answer"),
    title="Healthcare Q&A Bot",
    description="Ask common health-related questions and get answers."
)

# Launch the Gradio interface
interface.launch()