# -*- coding: utf-8 -*-
"""AI HEALTH CARE BOT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qhgb-BX5e-qpmmsaGqgXwmrvCtmwG0yL
"""

!pip install gradio

import gradio as gr

# Define the healthcare questions and answers
healthcare_qna = {
    "What are the symptoms of diabetes?": "Common symptoms of diabetes include frequent urination, excessive thirst, unexplained weight loss, fatigue, blurred vision, and slow-healing sores.",
    "How can I prevent heart disease?": "To prevent heart disease, maintain a healthy diet, exercise regularly, avoid smoking, manage stress, and keep blood pressure and cholesterol levels in check.",
    "What are the early signs of cancer?": "Early signs of cancer can vary depending on the type but may include unusual lumps or swelling, persistent pain, changes in skin or moles, unexplained weight loss, and persistent cough or hoarseness.",
    "What are the common symptoms of influenza (flu)?": "Symptoms of influenza include high fever, chills, muscle aches, cough, congestion, runny nose, headaches, and fatigue.",
    "How is hypertension treated?": "Hypertension is treated with lifestyle changes such as a healthy diet, regular exercise, and medications like diuretics, ACE inhibitors, or beta-blockers as prescribed by a doctor.",
    "What causes allergies and how can they be managed?": "Allergies are caused by an overreaction of the immune system to allergens such as pollen, dust, or certain foods. They can be managed with medications, avoiding allergens, and using air purifiers.",
    "What are the symptoms of asthma?": "Symptoms of asthma include shortness of breath, wheezing, chest tightness, and coughing, especially at night or early in the morning.",
    "How can I manage chronic pain?": "Chronic pain can be managed through medications, physical therapy, stress management techniques, and lifestyle changes such as regular exercise and a balanced diet.",
    "What are the common treatments for arthritis?": "Treatments for arthritis include medications to reduce inflammation and pain, physical therapy, regular exercise, and in some cases, surgical interventions.",
    "What are the symptoms of a stroke?": "Symptoms of a stroke can include sudden numbness or weakness in the face, arm, or leg, confusion, trouble speaking or understanding, trouble seeing in one or both eyes, and difficulty walking or loss of balance.",
    "How can I manage diabetes?": "Diabetes management includes monitoring blood sugar levels, following a healthy diet, engaging in regular physical activity, and adhering to prescribed medications or insulin therapy.",
    "What is the difference between type 1 and type 2 diabetes?": "Type 1 diabetes is an autoimmune condition where the body does not produce insulin, while type 2 diabetes is often related to insulin resistance and is more common in adults. Both require management of blood sugar levels.",
    "What are the symptoms of high blood pressure?": "High blood pressure often has no symptoms but may include headaches, shortness of breath, or nosebleeds in severe cases.",
    "How can I reduce stress?": "Stress can be reduced through regular physical activity, relaxation techniques, meditation, maintaining a balanced diet, and seeking support from friends or a mental health professional.",
    "What is a healthy diet?": "A healthy diet includes a variety of fruits, vegetables, whole grains, lean proteins, and healthy fats, while limiting processed foods, sugary drinks, and high-sodium products.",
    "What are common causes of fatigue?": "Common causes of fatigue include poor sleep, stress, nutritional deficiencies, chronic illnesses, and lack of physical activity.",
    "How can I improve my sleep quality?": "Improving sleep quality can involve maintaining a regular sleep schedule, creating a relaxing bedtime routine, limiting caffeine and electronic device use before bed, and ensuring a comfortable sleep environment.",
    "What are the signs of dehydration?": "Signs of dehydration include dry mouth, dark yellow urine, fatigue, dizziness, and confusion.",
    "How can I boost my immune system?": "Boosting the immune system involves eating a balanced diet rich in vitamins and minerals, getting regular exercise, staying hydrated, and getting adequate sleep.",
    "What is the role of exercise in health?": "Exercise improves cardiovascular health, strengthens muscles, enhances flexibility, aids in weight management, and contributes to mental well-being.",
    "How can I manage cholesterol levels?": "Cholesterol levels can be managed through a healthy diet low in saturated fats, regular physical activity, maintaining a healthy weight, and, if necessary, medications prescribed by a doctor."
}

# Function to display the answer
def healthcare_bot(question):
    answer = healthcare_qna.get(question, "Sorry, I don't have information on that topic.")
    return answer

# Create a dropdown interface with Gradio
interface = gr.Interface(
    fn=healthcare_bot,
    inputs=gr.Dropdown(choices=list(healthcare_qna.keys()), label="Select a question"),
    outputs=gr.Textbox(label="Answer"),
    title="Healthcare Q&A Bot",
    description="Ask common health-related questions and get answers."
)

# Launch the Gradio interface
interface.launch()











import gradio as gr
import random
from datetime import datetime

# --- Chatbot Logic ---
memory = {}
interesting_facts = [
    "Octopuses have three hearts!",
    "Bananas are berries, but strawberries aren't!",
    "Honey never spoils — archaeologists found 3000-year-old edible honey!"
]

def chatbot(user_input, history):
    user_input = user_input.lower()
    now = datetime.now().strftime("%H:%M:%S")

    if "hi" in user_input or "hello" in user_input:
        reply = "Hi there! I'm a chatbot here to assist you. What's your name?"
    elif "my name is" in user_input:
        name = user_input.split("my name is")[-1].strip()
        memory['name'] = name
        reply = f"Nice to meet you, {name}!"
    elif "what is your name" in user_input:
        reply = "I'm just a chatbot, so I don't have a name, but you can call me anything."
    elif "where are you from" in user_input:
        reply = "I'm from the digital world, always ready to chat!"
    elif "how are you" in user_input:
        reply = "I'm fine. How about you?"
    elif "do you have any hobbies" in user_input or "interests" in user_input:
        reply = "I'm always busy helping users, so my hobby is chatting with people like you!"
    elif "what did you eat today" in user_input or "what do you like to eat" in user_input:
        reply = "I don't eat, but I can help you find delicious recipes and food-related information."
    elif "favorite color" in user_input:
        reply = "I'm a chatbot, so I don't have personal preferences for colors."
    elif "do you enjoy listening to music" in user_input:
        reply = "I can't listen to music, but I'm here to chat about it!"
    elif "tell me a joke" in user_input or "another joke" in user_input:
        reply = "Why did the scarecrow win an award? Because he was outstanding in his field!"
    elif "tell me an interesting fact" in user_input:
        reply = random.choice(interesting_facts)
    elif "weather in" in user_input:
        reply = "I can help you with weather information soon. Stay tuned for updates!"
    elif "latest news" in user_input:
        reply = "I can help you with the latest news soon. Stay tuned for updates!"
    elif "translate" in user_input:
        reply = "I can help you with translations soon. Stay tuned for updates!"
    elif "what is the time now" in user_input:
        reply = now
    elif "bye" in user_input:
        reply = f"Goodbye, {memory.get('name', 'friend')}! Take care and have a great day!"
    else:
        reply = "I'm sorry, I didn't understand that. Can you please rephrase your sentence?"

    history = history or []
    history.append((user_input, reply))
    return history, history

# --- Healthcare Q&A Logic ---
healthcare_qna = {
    "What are the symptoms of COVID-19?": "Common symptoms include fever, dry cough, and tiredness.",
    "How can I lower my blood pressure?": "Eat a healthy diet, reduce sodium, and exercise regularly.",
    "What are the benefits of regular exercise?": "Improved mood, better heart health, and weight management.",
    "How much water should I drink a day?": "About 2-3 liters depending on your activity and climate.",
    "What is a balanced diet?": "A diet with fruits, vegetables, lean protein, whole grains, and healthy fats."
}

def healthcare_bot(question):
    return healthcare_qna.get(question, "Sorry, I don't have information on that topic.")

# --- Combined GUI with Gradio Blocks ---
with gr.Blocks(title="Chat + Healthcare Bot") as demo:
    with gr.Tab("Friendly Chatbot"):
        chatbot_ui = gr.Chatbot()
        msg = gr.Textbox(placeholder="Type your message here...")
        clear = gr.Button("Clear Chat")
        msg.submit(chatbot, inputs=[msg, chatbot_ui], outputs=[chatbot_ui, chatbot_ui])
        clear.click(lambda: ([], []), outputs=[chatbot_ui, chatbot_ui])

    with gr.Tab("Healthcare Q&A Bot"):
        question = gr.Dropdown(choices=list(healthcare_qna.keys()), label="Select a question")
        answer = gr.Textbox(label="Answer")
        question.change(fn=healthcare_bot, inputs=question, outputs=answer)

demo.launch()





import gradio as gr
import random
from datetime import datetime

memory = {}
interesting_facts = [
    "Octopuses have three hearts!",
    "Bananas are berries, but strawberries aren't!",
    "Honey never spoils — archaeologists found 3000-year-old edible honey!"
]

# Define some common selectable questions
selectable_questions = [
    "Hi",
    "What is your name?",
    "Where are you from?",
    "How are you?",
    "Do you have any hobbies?",
    "Tell me a joke",
    "Tell me an interesting fact",
    "What is the time now?",
    "Bye"
]

def chatbot(user_input, history):
    user_input = user_input.lower()
    now = datetime.now().strftime("%H:%M:%S")

    if "hi" in user_input or "hello" in user_input:
        reply = "Hi there! I'm a chatbot here to assist you. What's your name?"
    elif "my name is" in user_input:
        name = user_input.split("my name is")[-1].strip()
        memory['name'] = name
        reply = f"Nice to meet you, {name}!"
    elif "what is your name" in user_input:
        reply = "I'm just a chatbot, so I don't have a name, but you can call me anything."
    elif "where are you from" in user_input:
        reply = "I'm from the digital world, always ready to chat!"
    elif "how are you" in user_input:
        reply = "I'm fine. How about you?"
    elif "do you have any hobbies" in user_input or "interests" in user_input:
        reply = "I'm always busy helping users, so my hobby is chatting with people like you!"
    elif "what did you eat today" in user_input or "what do you like to eat" in user_input:
        reply = "I don't eat, but I can help you find delicious recipes and food-related information."
    elif "favorite color" in user_input:
        reply = "I'm a chatbot, so I don't have personal preferences for colors."
    elif "do you enjoy listening to music" in user_input:
        reply = "I can't listen to music, but I'm here to chat about it!"
    elif "tell me a joke" in user_input or "another joke" in user_input:
        reply = "Why did the scarecrow win an award? Because he was outstanding in his field!"
    elif "tell me an interesting fact" in user_input:
        reply = random.choice(interesting_facts)
    elif "weather in" in user_input:
        reply = "I can help you with weather information soon. Stay tuned for updates!"
    elif "latest news" in user_input:
        reply = "I can help you with the latest news soon. Stay tuned for updates!"
    elif "translate" in user_input:
        reply = "I can help you with translations soon. Stay tuned for updates!"
    elif "what is the time now" in user_input:
        reply = now
    elif "bye" in user_input:
        reply = f"Goodbye, {memory.get('name', 'friend')}! Take care and have a great day!"
    else:
        reply = "I'm sorry, I didn't understand that. Can you please rephrase your sentence?"

    history = history or []
    history.append((user_input, reply))
    return history, history

with gr.Blocks() as demo:
    gr.Markdown("## Chatbot with Dropdown Questions")

    chatbot_ui = gr.Chatbot()
    msg = gr.Textbox(placeholder="Type your message here...")
    dropdown = gr.Dropdown(choices=selectable_questions, label="Or select a question")
    clear = gr.Button("Clear")

    # Text submission
    msg.submit(chatbot, inputs=[msg, chatbot_ui], outputs=[chatbot_ui, chatbot_ui])

    # Dropdown question triggers chatbot
    dropdown.change(lambda x, h: chatbot(x, h), inputs=[dropdown, chatbot_ui], outputs=[chatbot_ui, chatbot_ui])

    # Clear chat
    clear.click(lambda: ([], []), outputs=[chatbot_ui, chatbot_ui])

demo.launch()

